image: ubuntu:latest

before_script:
   - add-apt-repository ppa:george-edison55/cmake-3.x -y
   - apt-get update -qq
   - apt-get install -qq cmake

my_project:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make