image: ubuntu:latest

stages:
  - build

before_script:
   - apt-get update
   - apt-get install -qq git build-essential cmake doxygen cppcheck

build:linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make
